[package]
name = "jerome"
version = "0.1.0"
authors = ["jawallace16 <Jeffrey Wallace>"]

[dependencies]
rand = "0.4"
ndarray = "0.11"
ndarray-rand = "0.7"
itertools = "0.7"
bidir-map = "1.0"
indexmap = "1.0"
